name: 'Go AWS Lambda Builder'
description: 'Build Go lambda zips'
author: Aaron Griffin
inputs:
  files:
    description: "Source files"
    required: true
  credentials:
    description: "Git credentials - https://git-scm.com/docs/git-credential-store"
    required: false
  directory:
    description: Relative path under $GITHUB_WORKSPACE where Cargo project is located
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh "${{ inputs.files }}" "${{ inputs.directory }}" "${{ inputs.credentials }}"
      shell: bash

branding:
  icon: box
  color: orange